package org.trzcinska;

public class Lorem {
    public static String BASE = "\n" +
            "\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae egestas urna. Fusce et viverra lacus. Mauris id scelerisque neque, et condimentum purus. In leo mauris, consectetur sed ultricies vitae, consectetur id justo. Maecenas sed ornare ligula. Suspendisse facilisis mauris eget consequat fermentum. Suspendisse erat est, laoreet vitae urna quis, venenatis mattis augue. Pellentesque ac porttitor quam. Maecenas posuere quam lacus, vel ornare erat elementum sed. Quisque finibus, mi vitae faucibus gravida, est mi iaculis enim, ac elementum felis est sit amet nulla. Aliquam molestie pulvinar tempus. Aenean non leo pellentesque justo consequat viverra.\n" +
            "\n" +
            "Pellentesque nec justo vulputate, dapibus arcu ut, interdum quam. Pellentesque justo eros, dapibus in tortor a, faucibus sollicitudin tellus. Suspendisse enim erat, commodo ac est at, euismod feugiat erat. Ut nec diam eu mi lacinia ullamcorper vitae sed orci. Vestibulum ac est sed risus scelerisque placerat ut id est. In sodales dignissim est, nec aliquam lorem aliquet et. Vivamus turpis nunc, iaculis non sapien quis, sodales interdum elit. Ut metus erat, dignissim quis libero nec, consectetur accumsan ex. Aenean pulvinar urna eget eros finibus, in malesuada urna bibendum. Cras vel risus nec est fringilla fringilla.\n" +
            "\n" +
            "Etiam vitae mi vel ligula feugiat faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum nunc nibh, egestas nec viverra in, scelerisque in neque. Nunc nec facilisis nibh, eu porta eros. Sed lacinia ac turpis vehicula porttitor. Quisque eleifend aliquet dui, at convallis dolor vestibulum sit amet. Aenean sed tristique justo. Phasellus ac leo libero. Vivamus mattis nisl mauris, a convallis diam hendrerit suscipit. Proin porta dolor sollicitudin ullamcorper aliquet. Curabitur semper lacus sed quam ultricies, vel gravida enim laoreet. Nam blandit finibus ipsum. Maecenas a mi at nisl maximus pretium vel sit amet nisi. Aenean ac dui vulputate odio scelerisque condimentum sit amet malesuada diam. Nullam gravida sed orci vitae mollis. Aliquam sit amet risus at lectus fermentum consequat ut quis massa.\n" +
            "\n" +
            "Suspendisse potenti. Nulla viverra massa quis auctor gravida. Aenean quis odio sit amet sem rhoncus commodo. Praesent vitae justo sed ante scelerisque viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla condimentum suscipit nulla. Duis posuere at risus posuere consectetur. Sed tincidunt et orci sit amet dapibus. Pellentesque ante metus, auctor quis ex sit amet, malesuada convallis nisi. Phasellus efficitur rutrum turpis non dignissim. Phasellus faucibus, risus ut hendrerit consequat, sapien purus aliquet dui, ut vestibulum felis diam non urna. Praesent dapibus id odio in elementum. Donec molestie tortor a turpis consectetur, bibendum cursus felis interdum. Aliquam euismod augue rhoncus rutrum venenatis.\n" +
            "\n" +
            "Quisque mollis, mauris ut eleifend aliquam, risus lacus commodo ligula, eu placerat sapien odio ac leo. Duis quis efficitur elit, ac gravida sem. Nam id sodales mi. Nam sed sapien imperdiet, luctus nunc id, dignissim urna. In tincidunt, libero vel tempus vehicula, ex eros placerat sapien, hendrerit efficitur nibh diam eu quam. Phasellus malesuada dolor varius fringilla bibendum. Nunc fermentum sapien eu nisi sodales, sit amet volutpat tortor congue. Vivamus et ante a eros blandit consequat. Sed nec metus laoreet, fringilla neque nec, vehicula lacus. In elementum ipsum ac velit aliquam luctus. Proin turpis eros, sagittis tempor sapien vitae, rutrum volutpat nisl. ";
}
